### ISSUE TITLE
Toggle Ribbon Icon

### ISSUE THREAD

**Issue by SZanlongo** [proog/obsidian-trash-explorer#4]
Right now, removing the trash icon from the ribbon via the Obsidian->Appearance->Ribbon Menu option doesn't work. Upon restarting, the icon re-appears. Since we also have the icon in the menu above the file pane, is there a way to disable the ribbon icon?

**Comment by proog** [comment]
Sounds annoying for sure ☹️ 

I can't reproduce this issue on desktop or mobile - the ribbon icon stays hidden after a restart. If you open the hidden `.obsidian/workspace.json` file in your vault it should contain something like this:

```json
  "left-ribbon": {
    "hiddenItems": {
      "obsidian-trash-explorer:Open trash explorer": true
    }
  },
```

Is this the case?
